### ISSUE TITLE
Failure to convert .ccx files

### ISSUE THREAD

**Issue by HinzundKunz** [sk1project/uniconvertor#1]
I have an old Corel Clipart Gallery where uniconvertor fails to convert many of the ccx files and also has numeral issues with color. I am willing to provide (tons of) sample files if needed.

**Comment by sk1project** [comment]
Hi!

Sorry for delay in responding! 
Please contact us on the project website
http://sk1project.org/contact.php

Samples are really good for CCX/CDRX file format support.

**Comment by HinzundKunz** [comment]
Where should I send them? I have several thousand that wouldn't convert... ;-) I could also upload them to a file server (Google, MS Live, Dropbox, Box - whatever you prefer).
