### ISSUE TITLE
What happend to 2.0-branch?

### ISSUE THREAD

**Issue by htgoebel** [sk1project/uniconvertor#2]
Hi,

it looks like there has been some 2.0-branch (or so) at google code. At least some Linux distros are delivering 2.0, see. http://svnweb.mageia.org/packages/cauldron/uniconvertor/releases/2.0/0.svn362.6.mga5/SPECS/uniconvertor.spec?revision=785477&view=markup.

What happened to this branch?

**Comment by sk1project** [comment]
Hi,

2.0 branch is here: https://github.com/sk1project/sk1-wx
As for sK1 and for UniConvertor.
