### ISSUE TITLE
CMX to any format clipping image

### ISSUE THREAD

**Issue by stnigg** [sk1project/uniconvertor#27]
I try to convert images of my Corel Mega Gallery I bought some decades ago. It seems uniconverter is unable to correctly translate the images as the result most often shows a clipped version of the image. I use the build for MacOS if that is of any difference.
I attached one such image as an example and the result as an png image. Output format does not seem to matter as I checked PDF, SVG and PNG. Regarding attached example: obviously the image of the CD should show the whole disc and not just half of it. I am unsure on how to further assist at this point. It would be nice if someone could verify the issue.

![CD005](https://user-images.githubusercontent.com/47662379/103161191-60f65400-47de-11eb-86c6-8c2475408265.png)

[CD005.CMX.zip](https://github.com/sk1project/uniconvertor/files/5743906/CD005.CMX.zip)

**Comment by sk1project** [comment]
Hi @stnigg We have checked attached example and found that actually the problem cause is in the clipart files but not in UniConvertor processing. Here is a screenshot of CorelDRAW with your sample file:
![cdr12](https://user-images.githubusercontent.com/13432939/106721115-eb677a00-660c-11eb-882b-64c52f1ce634.png)

And this is how sK1/UniConvertor processes this file:
![sk1_2](https://user-images.githubusercontent.com/13432939/106721258-19e55500-660d-11eb-9d60-972ff97812ce.png)

We have the same result as a CorelDRAW. So the CMX files are just created such manner. To resolve the problem we will add translation option `--fit-page-to-image` See issue https://github.com/sk1project/uniconvertor/issues/32

**Comment by sk1project** [comment]
@stnigg we have implemented required feature. Using latest build you can translate your files without clipping by such command:
```
uniconvertor --fit-page-to-image <source_file> <output_file>
```

**Comment by stnigg** [comment]
I could convert my test files successfully to SVG. The images are now a perfect fit without any border. On some pictures it "feels" a bit worrying depending on the subject but this fitting option really is a game changer. As far as I am concerned this issue I files is solved. THX very much. It is appreciated.
