### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by xissburg** [sk1project/uniconvertor#48]
When I run `python setup.py build` I get this

/home/xissburg/Downloads/uniconvertor-master/setup.py:42: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.core import setup
Traceback (most recent call last):
  File "/home/xissburg/Downloads/uniconvertor-master/setup.py", line 62, in <module>
    import utils.deb
  File "/home/xissburg/Downloads/uniconvertor-master/utils/deb.py", line 48
    print ret
    ^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

**Comment by VVD** [comment]
https://github.com/sk1project/uniconvertor/issues/19
