### ISSUE TITLE
Error installing nodejs on Windows

### ISSUE THREAD

**Issue by boussifas** [sk1project/uniconvertor#8]
Hello, i'm trying to install nodejs on my computer .First, i tried to execute the msi file downloaded from the official site , but the setup wizard ended prematurely because an error. I also tried to install it with chocolatey but i get an error occured during installation : 
          # " Path  '....\nodejs.install\tools' is denied
Someone help me please

**Comment by XmlmXmlmX** [comment]
It sound like a problem with nodejs, and not with uniconverter itself. You should post your bug better here: https://github.com/nodejs/node/issues
